name: Trigger auto deployment for safetyshift

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/safetyshift-AutoDeployTrigger-5cddf563-4fc3-4311-9c96-6e17d6da4114.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SAFETYSHIFT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SAFETYSHIFT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SAFETYSHIFT_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SAFETYSHIFT_REGISTRY_USERNAME }}
          password: ${{ secrets.SAFETYSHIFT_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.SAFETYSHIFT_REGISTRY_USERNAME }}/safetyshift:${{ github.sha }}
            ${{ secrets.SAFETYSHIFT_REGISTRY_USERNAME }}/safetyshift:latest

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: docker.io/${{ secrets.SAFETYSHIFT_REGISTRY_USERNAME }}/safetyshift:${{ github.sha }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.SAFETYSHIFT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAFETYSHIFT_REGISTRY_PASSWORD }}
          containerAppName: safetyshift
          resourceGroup: Safetyshift
          targetPort: 80
          ingress: external
